### ISSUE TITLE
Broken link. Contribute page.

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestormjs.github.io#1]
[**Contributing rules**](http://whitestormjs.xyz/contribute) page doesn't work. It just downloads from server and doesn't open.

**Comment by jackdalton** [comment]
Interesting, it works locally, but not on GitHub Pages: 
![whitestormjs 3d engine - google chrome_001](https://cloud.githubusercontent.com/assets/10249860/12380260/f72f70ac-bd2b-11e5-98a8-32aca09d79b7.png)

**Comment by sasha240100** [comment]
@jackdalton Maybe it's an access error, something like block by .htaccess but in jekyll :eyes:

**Comment by jackdalton** [comment]
@sasha240100 Exactly what I was thinking. According to Postman, `/contribute`'s `Content-Type` is `application/octet-stream`, rather than `text/html`.

![selection_002](https://cloud.githubusercontent.com/assets/10249860/12380302/19bee34a-bd2d-11e5-8952-f48077e59e66.png)

**Comment by jackdalton** [comment]
Locally, it's exactly as expected:

![selection_003](https://cloud.githubusercontent.com/assets/10249860/12380314/7ec50d8c-bd2d-11e5-959f-a707fb8bf5aa.png)

**Comment by sasha240100** [comment]
@jackdalton Why is it so?

**Comment by jackdalton** [comment]
@sasha240100 I'm not too sure. I wonder if it could be related to jekyll/jekyll#406, or if that _only_ pertains to SVG files.

**Comment by jackdalton** [comment]
That did it, very nice.
