### ISSUE TITLE
http://whitestormjs.xyz/#shape material property seems to be a little confused

### ISSUE THREAD

**Issue by nhemsley** [WhitestormJS/whitestormjs.github.io#10]
the explanation says 'Fog Type', can be regular or expodential

then the next line says material type..

FYI

Cheers

**Comment by sasha240100** [comment]
@nhemsley Which line? Can you give a screenshot?

**Comment by nhemsley** [comment]
![screenshot from 2016-07-20 20-32-26](https://cloud.githubusercontent.com/assets/241697/16986571/cc14783e-4eb9-11e6-8804-9e45c26009cf.png)

Seems to be from malformed html, sorry I cant quite get my head around dealing with a hanging html tag, but I hope this helps!

**Comment by sasha240100** [comment]
@nhemsley Thanks for reporting, it's my typo. Will fix it now

**Comment by nhemsley** [comment]
@sasha240100 no problems. 

I quite like the look of whitestorm, it removes quite alot of typing overhead, always good.

Chers

**Comment by sasha240100** [comment]
@nhemsley Thanks! We are growing open source community and we hope that we will grow faster. If you like this project - best thing that you can do is to develop an application with it and share it with us and others:)
