### ISSUE TITLE
What happened to the URL?

### ISSUE THREAD

**Issue by impressivewebs** [WhitestormJS/whitestormjs.github.io#11]
This was working yesterday:

https://whitestormjs.xyz/

Have you changed the URL? It doesn't seem to working right now. That's the URL I used when I included your framework [in my newsletter](http://us5.campaign-archive2.com/?u=ea228d7061e8bbfa8639666ad&id=af05122527).

**Comment by sasha240100** [comment]
@impressivewebs use the new one: https://whsjs.io/

**Comment by impressivewebs** [comment]
Sorry, the newsletter issue had already gone out. I'll correct it in the archive but maybe I'll include it again in the near future to make up for it. But what happened to the old URL? You can't redirect? Did someone steal it or something?

**Comment by sasha240100** [comment]
@impressivewebs We just moved from that one to a new one (shorter one)

**Comment by sasha240100** [comment]
@impressivewebs I am really sorry for such discomfort. Yep, maybe I will make a redirect this week

**Comment by impressivewebs** [comment]
It's not a problem. I was just feeling bad that you missed out on some traffic from my newsletter (which has 12,000+ subscribers). Anyhow, like I said, I'll include it again at a later date with the new URL.

**Comment by sasha240100** [comment]
@impressivewebs Bought http://whitestormjs.xyz/ again. Should redirect now to a new domain, check.
**It will be awesome if you include new link in next newsletter** cause we are planing some updates till that time _(maybe a new release)_

**Comment by sasha240100** [comment]
Https redirect doesn't work yet, cause there is no ssl
