### ISSUE TITLE
'npm install whs' spacing on landing page

### ISSUE THREAD

**Issue by mscdex** [WhitestormJS/whitestormjs.github.io#13]
On the landing page there is no space between 'install' and 'whs' of 'npm install whs', so it just looks like 'npm installwhs'. FWIW I was viewing from Linux with Chrome 54.

Adding a `margin-left: 20px` or so to the 'whs' link made it look more evenly spaced.

**Comment by yeliex** [comment]
fixed in https://github.com/WhitestormJS/whitestormjs.github.io/commit/94c25af4a08b9ee0832df9d7b65c4d8e4c225052

**Comment by mscdex** [comment]
I'm not seeing any change in the styling on the site, do the changes have to be deployed first or ?

**Comment by yeliex** [comment]
@mscdex can you provide a screenshot

**Comment by mscdex** [comment]
Here is what I'm seeing:

![whsjsio-landing-page](https://cloud.githubusercontent.com/assets/54666/20868958/4b22bb6c-ba36-11e6-9f9f-ba4213ab8672.png)

**Comment by hirako2000** [comment]
this is fixed.

**Comment by mscdex** [comment]
@hirako2000 It still looks the same.

**Comment by hirako2000** [comment]
what browser and OS are you using?

**Comment by mscdex** [comment]
@hirako2000 Linux and Chrome 58.0.3029.81 64-bit.

**Comment by hirako2000** [comment]
hmm, the only thing I can see, is that it's using a [hair space](http://www.fileformat.info/info/unicode/char/200a/index.htm). 
It's interesting that most browsers make this unicode take the width of a normal space, but on Linux make it look like the width of a hair literally...

I will replace this as I'm making other changes. thanks for re-reporting it :)

**Comment by mscdex** [comment]
@hirako2000 Ah yes, I was just about to report that. [According to wikipedia (U+200A)](https://en.wikipedia.org/wiki/Whitespace_character), the description for this character is "thinner than a thin space" which I think quite accurately describes it here, so Linux/Chrome is in the right here :-)

**Comment by hirako2000** [comment]
Yep, probably a more experimental build than binaries for other OS. 

> hair space is not universally supported in browsers yet
