### ISSUE TITLE
Sometimes i see broken github buttons

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whitestormjs.github.io#2]
Sometimes i see these broken github buttons, sometime not... but i want to fix it.
![](https://www.diigo.com/file/image/scrbecbzdabdbaecszcaorcqer/WhitestormJS+3D+Engine.jpg)

**Comment by electron0zero** [comment]
@sasha240100 is this issue fixed, can we close it ?

**Comment by sasha240100** [comment]
@electron0zero yes. New website
