### ISSUE TITLE
iOS crashes (mobile)

### ISSUE THREAD

**Issue by preco21** [WhitestormJS/whitestormjs.github.io#9]
OS: iOS 9.3.1
Browser: Chrome for iOS, Safari

Page causes crash every 10-20 secs on iOS mobile.

![image](https://cloud.githubusercontent.com/assets/4936201/14802913/ca22879a-0b8f-11e6-979d-ae04f3bbb076.png)

**Comment by sasha240100** [comment]
@preco21 Thanks for submitting this issue. Fixed!

**Comment by preco21** [comment]
@sasha240100 It seems like still not working properly, which has even timed out. But works fine on desktop.

**Comment by preco21** [comment]
@sasha240100 Ah, sorry for misreporting. Now it works fine.

**Comment by sasha240100** [comment]
@preco21 Should work. Maybe you have data saver turned on?
Can you please open sidebar (menu) and make a screenshot? If you have "output" option near "html" and "JavaScript " - it's a cached one and you need to refresh site.

**Comment by preco21** [comment]
@sasha240100 There is no `output` option on sidebar menu. Even after refreshing the site.

![photo_2016-04-26_17-48-53](https://cloud.githubusercontent.com/assets/4936201/14812254/559df33a-0bd7-11e6-8267-d4b5ef789476.jpg)

**Comment by sasha240100** [comment]
@preco21 It should work properly if so.

---

Tested with my **Nexus 5x**

**Comment by preco21** [comment]
@sasha240100 It doesn't work on desktop browser too. I have used Chrome, Chrome Canary for testing. Also, cache is cleaned.

**Comment by sasha240100** [comment]
@preco21 Can you provide some logs from console before it crashes? Can i access your pc with teamviewer?

**Comment by preco21** [comment]
@sasha240100 I'm comming home now. Once I arrived, I will let you know.

**Comment by preco21** [comment]
@sasha240100 Here is the log:

![image 001](https://cloud.githubusercontent.com/assets/4936201/14815322/a9729e94-0be5-11e6-89c0-5a76d4701121.png)

**Comment by sasha240100** [comment]
@preco21 Nothing there. Should work. Can you join our slack so we can discuss it further in realtime? http://whslack.herokuapp.com/
